### ISSUE TITLE
Add an Angular Service for API calls to Cuisine 

### ISSUE THREAD

**Issue by GorillaJulz** [Event-Riddle/MenuCard#8]
Cuisine should have a Service which is responsible for API calls. It acts as an interface between the controller and the API to make call transparent.

**Comment by Babis86** [comment]
Interface for the get call was aded, as a angular servcie

```
angular
      .module('riddle.detail')
      .provider('APIService', apiService);

      apiService.$inject=['$resourceProvider'];
```

**Comment by Babis86** [comment]
TODO: function for post call #13
